# db config
# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board11
    username: root
    password: green502
    jdbc-url: jdbc:mariadb://localhost:3306/board11

# mybatis config
mybatis:
  type-aliases-package: com.green.board11_2
  mapper-locations: mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: download/board10

